name: 'lab02_18105793'
version: '1.0.0'
config-version: 2

profile: 'lab02'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  lab02_nusp:
    staging:
      +materialized: view
      +schema: staging

    marts:
      +materialized: table
      +schema: gold
